package day41;

import java.time.Duration;
import java.util.Set;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterClass;
import org.testng.annotations.Test;
import org.openqa.selenium.Cookie;

public class CookiesDemo {

	WebDriver driver;

	@Test
	void setUp() {
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
		driver.get("https://demo.nopcommerce.com/");
	}

	@Test
	void testCookies() {
		// How To capture cookies from browser?
		Set<Cookie> cookies = driver.manage().getCookies();
		System.out.println("Size of cookies:" + cookies.size()); // 3

		// How To print cookies from browser?
		for (Cookie c : cookies) {
			System.out.println(c.getName() + ":" + c.getValue());
		}

		// How To add Cookie to the browser?
		Cookie cookieobj = new Cookie("Mycookie", "123456");
		driver.manage().addCookie(cookieobj);
		cookies = driver.manage().getCookies();
		System.out.println("Size of cookies after adding new one:" + cookies.size());

		// How To delete specific Cookie from the browser?
		// driver.manage().deleteCookie(cookieobj); // deleting my own cookie
		driver.manage().deleteCookieNamed(".Nop.Customer"); // delete cookie which generated by browser..

		cookies = driver.manage().getCookies();
		System.out.println("Size of cookies after deletion of new one:" + cookies.size());

		// How To delete all Cookies from the browser?
		driver.manage().deleteAllCookies();
		cookies = driver.manage().getCookies();
		System.out.println("Size of cookies after deletion of all:" + cookies.size());
	}

	@AfterClass
	void tearDown() {
		driver.quit();
	}

}
